services:
  # Core infrastructure services
  etcd:
    image: bitnami/etcd:3.5.14-debian-12-r1
    container_name: Etcd-server
    ports:
      - "2379:2379"
      - "2380:2380"
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_ADVERTISE_CLIENT_URLS=http://localhost:2379
    deploy:
      resources:
        limits:
          cpus: '1'
    restart: unless-stopped

  prometheus:
    image: prom/prometheus:v2.37.1
    container_name: prometheusLocal
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    restart: unless-stopped

  serverledge:
    build:
      context: serverledge
      dockerfile: Dockerfile
    image: serverledge:latest
    container_name: serverledge
    ports:
      - "1323:1323"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:rw
      - ./serverledge/conf.yaml:/app/conf.yaml:rw
    depends_on:
      - etcd
      - prometheus
    restart: no

  # FIGARO services
  figaro-agent:
    build:
      context: .
      dockerfile: figaro/agent/src/production_agents/DQN/Dockerfile
    image: figaro-production_agent:latest
    container_name: figaro-agent
    ports:
      - "5100:5000"
    restart: unless-stopped

  figaro-controller:
    build:
      context: .
      dockerfile: figaro/controller/Dockerfile
    image: figaro-controller:latest
    container_name: figaro-controller
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:rw
      - ./logs:/app/logs:rw
    restart: unless-stopped
    depends_on:
      - etcd
      - prometheus
      - figaro-agent

  # Videosearcher function images (these are built but not run as services)
  # These are run by serverledge on demand
  ffmpeg_0:
    build:
      context: .
      dockerfile: figaro/videosearcher/ffmpeg_0/Dockerfile
    image: ffmpeg_0:latest
    profiles:
      - build-only  # This profile prevents the service from starting by default

  ffmpeg_1:
    build:
      context: .
      dockerfile: figaro/videosearcher/ffmpeg_1/Dockerfile
    image: ffmpeg_1:latest
    profiles:
      - build-only

  ffmpeg_2:
    build:
      context: .
      dockerfile: figaro/videosearcher/ffmpeg_2/Dockerfile
    image: ffmpeg_2:latest
    profiles:
      - build-only

  librosa:
    build:
      context: .
      dockerfile: figaro/videosearcher/librosa/Dockerfile
    image: librosa:latest
    profiles:
      - build-only

  deepspeech:
    build:
      context: .
      dockerfile: figaro/videosearcher/deepspeech/Dockerfile
    image: deepspeech:latest
    profiles:
      - build-only

  grep:
    build:
      context: .
      dockerfile: figaro/videosearcher/grep/Dockerfile
    image: grep:latest
    profiles:
      - build-only
