apiVersion: batch/v1
kind: Job
metadata:
  name: jmeter-test
spec:
  template:
    spec:
      containers:
      - name: jmeter
        image: jmeter:latest  # Replace with your registry path
        command: ["/bin/bash", "/config/run-test.sh"]
        imagePullPolicy: Never
        env:
        - name: TEST_PLAN
          value: "jmeter.jmx"  # Replace with your actual test plan name
        volumeMounts:
        - name: config-volume
          mountPath: /config
        - name: results-volume
          mountPath: /jmeter/results
        resources:
          requests:
            memory: "512Mi"
            cpu: "1"
          limits:
            memory: "1Gi"
            cpu: "2" #maxmimum of two cores used
      volumes:
      - name: config-volume
        configMap:
          name: jmeter-config
          defaultMode: 0777  # Make the script executable
      - name: results-volume
        persistentVolumeClaim:
          claimName: jmeter-results-pvc
      restartPolicy: Never
  backoffLimit: 1