services:
  agent_cl1_triple_layer_S4AID:
    container_name: agent_cl1_triple_layer_S4AID
    restart: always
    image: production_agent:latest
    ports:
      - "5009:5000"
    networks:
      - net_triple_layer_S4AID
    volumes:
      - ${PWD}/../../../src/production_agents/DQN/agent_server_DQN.py:/app/agent_server.py
      - ${PWD}/../../../src/production_agents/DQN/production_agent_DQN.py:/app/production_agent_DQN.py
      - ${PWD}/../../../RL4CC:/app/RL4CC
      - ${PWD}/../../../src:/app/src
      - ${PWD}/configuration_files/checkpoints/trained_checkpoint_cl1:/app/trained_checkpoint/
networks:
  net_triple_layer_S4AID:
    name: net_triple_layer_S4AID
    #external: true
