metrics:
  enabled: true
container:
  pool:
    cpus: 2
    memory: 1024
api:
  port: 1324
cloud:
  server:
    url: http://192.168.1.21:1325
scheduler:
  policy: customCloudOffload
registry:
  udp:
    port: 9877